; ===========================================================================
; ║                                                                         ║
; ║                             SONIC&K SOUND DRIVER                        ║
; ║                         Modified SMPS Z80 Type 2 DAC                    ║
; ║                                                                         ║
; ===========================================================================
; Disassembled by MarkeyJester
; Routines, pointers and stuff by Linncaki
; Thoroughly commented and improved (including optional bugfixes) by Flamewing
; ===========================================================================
; Permission to use, copy, modify, and/or distribute this software for any
; purpose with or without fee is hereby granted.
;
; THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
; WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
; MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
; ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
; WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
; ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT
; OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
; ===========================================================================
; Sound Bank
; ===========================================================================
SndBank:			startBank

; ===========================================================================
; SFX Pointers
; ===========================================================================
		Snd_Master_Table
; ---------------------------------------------------------------------------
SEGA_PCM:	binclude "Sound/Sega PCM.bin"
SEGA_PCM_End
		even
Sound_RingRight:			include "Sound/sksfx/33 - Ring (Right).asm"
Sound_RingLeft:				include "Sound/sksfx/34 - Ring (Left).asm"
Sound_Death:				include "Sound/sksfx/35 - Death.asm"
Sound_Skid:					include "Sound/sksfx/36 - Skid.asm"
Sound_SpikeHit:				include "Sound/sksfx/37 - Spike Hit.asm"
Sound_Bubble:				include "Sound/sksfx/38 - Bubble.asm"
Sound_Splash:				include "Sound/sksfx/39 - Splash.asm"
Sound_Shield:				include "Sound/sksfx/3A - Shield.asm"
Sound_Drown:				include "Sound/sksfx/3B - Drown.asm"
Sound_Roll:					include "Sound/sksfx/3C - Roll.asm"
Sound_Break:				include "Sound/sksfx/3D - Break.asm"
Sound_FireShield:			include "Sound/sksfx/3E - Fire Shield.asm"
Sound_BubbleShield:			include "Sound/sksfx/3F - Bubble Shield.asm"
Sound_UnknownShield:		include "Sound/sksfx/40 - Unknown Shield.asm"
Sound_LightningShield:		include "Sound/sksfx/41 - Lightning Shield.asm"
Sound_InstaAttack:			include "Sound/sksfx/42 - Insta Shield Attack.asm"
Sound_FireAttack:			include "Sound/sksfx/43 - Fire Shield Attack.asm"
Sound_BubbleAttack:			include "Sound/sksfx/44 - Bubble Shield Attack.asm"
Sound_ElectricAttack:		include "Sound/sksfx/45 - Lightning Shield Attack.asm"
Sound_Whistle:				include "Sound/sksfx/46 - Whistle.asm"
Sound_SandwallRise:			include "Sound/sksfx/47 - Sand Wall Rise.asm"
Sound_Blast:				include "Sound/sksfx/48 - Blast.asm"
Sound_Thump:				include "Sound/sksfx/49 - Thump.asm"
Sound_Grab:					include "Sound/sksfx/4A - Grab.asm"
Sound_WaterfallSplash:		include "Sound/sksfx/4B - Waterfall Splash.asm"
Sound_GlideLand:			include "Sound/sksfx/4C - Glide Land.asm"
Sound_Projectile:			include "Sound/sksfx/4D - Projectile.asm"
Sound_MissileExplode:		include "Sound/sksfx/4E - Missile Explode.asm"
Sound_FlamethrowerQuiet:	include "Sound/sksfx/4F - Flamethrower (Quiet).asm"
Sound_BossActivate:			include "Sound/sksfx/50 - Boss Activate.asm"
Sound_MissileThrow:			include "Sound/sksfx/51 - Missile Throw.asm"
Sound_SpikeMove:			include "Sound/sksfx/52 - Spike Move.asm"
Sound_Charging:				include "Sound/sksfx/53 - Charging.asm"
Sound_BossLaser:			include "Sound/sksfx/54 - Boss Laser.asm"
Sound_BlockConveyor:		include "Sound/sksfx/55 - Block Conveyor.asm"
Sound_FlipBridge:			include "Sound/sksfx/56 - Flip Bridge.asm"
Sound_Geyser:				include "Sound/sksfx/57 - Geyser.asm"
Sound_FanLatch:				include "Sound/sksfx/58 - Fan Latch.asm"
Sound_Collapse:				include "Sound/sksfx/59 - Collapse.asm"
Sound_UnknownCharge:		include "Sound/sksfx/5A - Unknown Charge.asm"
Sound_Switch:				include "Sound/sksfx/5B - Switch.asm"
Sound_MechaSpark:			include "Sound/sksfx/5C - Mecha Spark.asm"
Sound_FloorThump:			include "Sound/sksfx/5D - Floor Thump.asm"
Sound_Laser:				include "Sound/sksfx/5E - Laser.asm"
Sound_Crash:				include "Sound/sksfx/5F - Crash.asm"
Sound_BossZoom:				include "Sound/sksfx/60 - Boss Zoom.asm"
Sound_BossHitFloor:			include "Sound/sksfx/61 - Boss Hit Floor.asm"
Sound_Jump:					include "Sound/sksfx/62 - Jump.asm"
Sound_Starpost:				include "Sound/sksfx/63 - Star Post.asm"
Sound_PulleyGrab:			include "Sound/sksfx/64 - Pulley Grab.asm"
Sound_BlueSphere:			include "Sound/sksfx/65 - Blue Sphere.asm"
Sound_AllSpheres:			include "Sound/sksfx/66 - All Spheres Collected.asm"
Sound_LevelProjectile:		include "Sound/sksfx/67 - Level Projectile.asm"
Sound_Perfect:				include "Sound/sksfx/68 - Perfect.asm"
Sound_PushBlock:			include "Sound/sksfx/69 - Push Block.asm"
Sound_Goal:					include "Sound/sksfx/6A - Goal.asm"
Sound_ActionBlock:			include "Sound/sksfx/6B - Action Block.asm"
Sound_Splash2:				include "Sound/sksfx/6C - Splash 2.asm"
Sound_UnknownShift:			include "Sound/sksfx/6D - Unknown Shift.asm"
Sound_BossHit:				include "Sound/sksfx/6E - Boss Hit.asm"
Sound_Rumble2:				include "Sound/sksfx/6F - Rumble 2.asm"
Sound_LavaBall:				include "Sound/sksfx/70 - Lava Ball.asm"
Sound_Shield2:				include "Sound/sksfx/71 - Shield 2.asm"
Sound_Hoverpad:				include "Sound/sksfx/72 - Hoverpad.asm"
Sound_Transporter:			include "Sound/sksfx/73 - Transporter.asm"
Sound_TunnelBooster:		include "Sound/sksfx/74 - Tunnel Booster.asm"
Sound_BalloonPlatform:		include "Sound/sksfx/75 - Balloon Platform.asm"
Sound_TrapDoor:				include "Sound/sksfx/76 - Trap Door.asm"
Sound_Balloon:				include "Sound/sksfx/77 - Balloon.asm"
Sound_GravityMachine:		include "Sound/sksfx/78 - Gravity Machine.asm"
Sound_Lightning:			include "Sound/sksfx/79 - Lightning.asm"
Sound_BossMagma:			include "Sound/sksfx/7A - Boss Magma.asm"
Sound_SmallBumpers:			include "Sound/sksfx/7B - Small Bumpers.asm"
Sound_ChainTension:			include "Sound/sksfx/7C - Chain Tension.asm"
Sound_UnknownPump:			include "Sound/sksfx/7D - Unknown Pump.asm"
Sound_GroundSlide:			include "Sound/sksfx/7E - Ground Slide.asm"
Sound_FrostPuff:			include "Sound/sksfx/7F - Frost Puff.asm"
Sound_IceSpikes:			include "Sound/sksfx/80 - Ice Spikes.asm"
Sound_TubeLauncher:			include "Sound/sksfx/81 - Tube Launcher.asm"
Sound_SandSplash:			include "Sound/sksfx/82 - Sand Splash.asm"
Sound_BridgeCollapse:		include "Sound/sksfx/83 - Bridge Collapse.asm"
Sound_UnknownPowerUp:		include "Sound/sksfx/84 - Unknown Power-Up.asm"
Sound_UnknownPowerDown:		include "Sound/sksfx/85 - Unknown Power-Down.asm"
Sound_Alarm:				include "Sound/sksfx/86 - Alarm.asm"
Sound_MushroomBounce:		include "Sound/sksfx/87 - Mushroom Bounce.asm"
Sound_PulleyMove:			include "Sound/sksfx/88 - Pulley Move.asm"
Sound_WeatherMachine:		include "Sound/sksfx/89 - Weather Machine.asm"
Sound_Bouncy:				include "Sound/sksfx/8A - Bouncy.asm"
Sound_ChopTree:				include "Sound/sksfx/8B - Chop Tree.asm"
Sound_ChopStuck:			include "Sound/sksfx/8C - Chop Stuck.asm"
Sound_UnknownFlutter:		include "Sound/sksfx/8D - Unknown Flutter.asm"
Sound_UnknownRevving:		include "Sound/sksfx/8E - Unknown Revving.asm"
Sound_DoorOpen:				include "Sound/sksfx/8F - Door Open.asm"
Sound_DoorMove:				include "Sound/sksfx/90 - Door Move.asm"
Sound_DoorClose:			include "Sound/sksfx/91 - Door Close.asm"
Sound_GhostAppear:			include "Sound/sksfx/92 - Ghost Appear.asm"
Sound_BossRecovery:			include "Sound/sksfx/93 - Boss Recovery.asm"
Sound_ChainTick:			include "Sound/sksfx/94 - Chain Tick.asm"
Sound_BossHand:				include "Sound/sksfx/95 - Boss Hand.asm"
Sound_MechaLand:			include "Sound/sksfx/96 - Mecha Land.asm"
Sound_EnemyBreath:			include "Sound/sksfx/97 - Enemy Breath.asm"
Sound_BossProjectile:		include "Sound/sksfx/98 - Boss Projectile.asm"
Sound_UnknownPlink:			include "Sound/sksfx/99 - Unknown Plink.asm"
Sound_SpringLatch:			include "Sound/sksfx/9A - Spring Latch.asm"
Sound_ThumpBoss:			include "Sound/sksfx/9B - Thump Boss (Sonic & Knuckles).asm"
Sound_SuperEmerald:			include "Sound/sksfx/9C - Super Emerald.asm"
Sound_Targeting:			include "Sound/sksfx/9D - Targeting.asm"
Sound_Clank:				include "Sound/sksfx/9E - Clank.asm"
Sound_SuperTransform:		include "Sound/sksfx/9F - Super Transform.asm"
Sound_MissileShoot:			include "Sound/sksfx/A0 - Missile Shoot.asm"
Sound_UnknownOminous:		include "Sound/sksfx/A1 - Unknown Ominous.asm"
Sound_FloorLauncher:		include "Sound/sksfx/A2 - Floor Launcher.asm"
Sound_GravityLift:			include "Sound/sksfx/A3 - Gravity Lift.asm"
Sound_MechaTransform:		include "Sound/sksfx/A4 - Mecha Transform.asm"
Sound_UnknownRise:			include "Sound/sksfx/A5 - Unknown Rise.asm"
Sound_LaunchGrab:			include "Sound/sksfx/A6 - Launch Grab.asm"
Sound_LaunchReady:			include "Sound/sksfx/A7 - Launch Ready.asm"
Sound_EnergyZap:			include "Sound/sksfx/A8 - Energy Zap.asm"
Sound_AirDing:				include "Sound/sksfx/A9 - Air Ding.asm"
Sound_Bumper:				include "Sound/sksfx/AA - Bumper.asm"
Sound_Spindash:				include "Sound/sksfx/AB - Spin Dash.asm"
Sound_Continue:				include "Sound/sksfx/AC - Continue.asm"
Sound_LaunchGo:				include "Sound/sksfx/AD - Launch Go (Sonic & Knuckles).asm"
Sound_Flipper:				include "Sound/sksfx/AE - Flipper.asm"
Sound_EnterSS:				include "Sound/sksfx/AF - Enter Special Stage.asm"
Sound_Register:				include "Sound/sksfx/B0 - Register.asm"
Sound_Spring:				include "Sound/sksfx/B1 - Spring.asm"
Sound_Error:				include "Sound/sksfx/B2 - Error.asm"
Sound_BigRing:				include "Sound/sksfx/B3 - Big Ring.asm"
Sound_Explode:				include "Sound/sksfx/B4 - Explode.asm"
Sound_Diamonds:				include "Sound/sksfx/B5 - Diamonds.asm"
Sound_Dash:					include "Sound/sksfx/B6 - Dash.asm"
Sound_SlotMachine:			include "Sound/sksfx/B7 - Slot Machine.asm"
Sound_Signpost:				include "Sound/sksfx/B8 - Signpost.asm"
Sound_RingLoss:				include "Sound/sksfx/B9 - Ring Loss.asm"
Sound_Flying:				include "Sound/sksfx/BA - Flying.asm"
Sound_FlyTired:				include "Sound/sksfx/BB - Flying (Tired).asm"
Sound_SlideSkidLoud:		include "Sound/sksfx/BC - Slide Skid (Loud).asm"
Sound_LargeShip:			include "Sound/sksfx/BD - Large Ship.asm"
Sound_RobotnikSiren:		include "Sound/sksfx/BE - Robotnik Siren.asm"
Sound_BossRotate:			include "Sound/sksfx/BF - Boss Rotate.asm"
Sound_FanBig:				include "Sound/sksfx/C0 - Fan (Big).asm"
Sound_FanSmall:				include "Sound/sksfx/C1 - Fan (Small).asm"
Sound_FlamethrowerLoud:		include "Sound/sksfx/C2 - Flamethrower (Loud).asm"
Sound_GravityTunnel:		include "Sound/sksfx/C3 - Gravity Tunnel.asm"
Sound_BossPanic:			include "Sound/sksfx/C4 - Boss Panic.asm"
Sound_UnknownSpin:			include "Sound/sksfx/C5 - Unknown Spin.asm"
Sound_WaveHover:			include "Sound/sksfx/C6 - Wave Hover.asm"
Sound_CannonTurn:			include "Sound/sksfx/C7 - Cannon Turn.asm"
Sound_SlideSkidQuiet:		include "Sound/sksfx/C8 - Slide Skid (Quiet).asm"
Sound_SpikeBalls:			include "Sound/sksfx/C9 - Spike Balls.asm"
Sound_LightTunnel:			include "Sound/sksfx/CA - Light Tunnel.asm"
Sound_Rumble:				include "Sound/sksfx/CB - Rumble.asm"
Sound_BigRumble:			include "Sound/sksfx/CC - Big Rumble.asm"
Sound_DeathEggRiseLoud:		include "Sound/sksfx/CD - Death Egg Rise (Loud).asm"
Sound_WindQuiet:			include "Sound/sksfx/CE - Wind (Quiet).asm"
Sound_WindLoud:				include "Sound/sksfx/CF - Wind (Loud).asm"
Sound_Rising:				include "Sound/sksfx/D0 - Rising.asm"
Sound_UnknownFlutter2:		include "Sound/sksfx/D1 - Unknown Flutter 2.asm"
Sound_GumballTab:			include "Sound/sksfx/D2 - Gumball Tab.asm"
Sound_DeathEggRiseQuiet:	include "Sound/sksfx/D3 - Death Egg Rise (Quiet).asm"
Sound_TurbineHum:			include "Sound/sksfx/D4 - Turbine Hum.asm"
Sound_LavaFall:				include "Sound/sksfx/D5 - Lava Fall.asm"
Sound_UnknownZap:			include "Sound/sksfx/D6 - Unknown Zap.asm"
Sound_ConveyorPlatform:		include "Sound/sksfx/D7 - Conveyor Platform.asm"
Sound_UnknownSaw:			include "Sound/sksfx/D8 - Unknown Saw.asm"
Sound_MagneticSpike:		include "Sound/sksfx/D9 - Magnetic Spike.asm"
Sound_LeafBlower:			include "Sound/sksfx/DA - Leaf Blower.asm"
Sound_WaterSkid:			include "Sound/sksfx/DB - Water Skid.asm"

	finishBank
; ---------------------------------------------------------------------------
